baseURL = 'https://adi4blogs.netlify.app/'
languageCode = 'en-us'
title = 'Adiboy Blogs'
theme = "flat"
enableRobotsTXT = true
hasCJKLanguage = true
paginate = 4

# these values are hugo built in markup config
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = false
noClasses = false
noHl = false
style = 'monokailight'
tabWidth = 4

[params]
description = "Blogs by Aditya Ranjan Jha"
mainSections = ['posts']

## uncomment belows and set proper values to enable remark42
# [params.remark42]
# host=''
# site_id=''
# max_shown_comments=100
# theme='light'
# locale='en'
# show_email_subscription=false
# simple_view=true


# you can set multi row of footers like these
[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Author"
url = "https://github.com/Adiboy3112"
pre = "With ❤️ <a href=\"https://www.linkedin.com/in/adiboy/\">Aditya Ranjan Jha</a>"


[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Mozilla Public License Version 2.0"
url = "https://github.com/Adiboy3112/My-Blogs/blob/master/LICENSE"
pre = "Copyright <a href=\"https://github.com/Adiboy3112/My-Blogs/blob/master/LICENSE\">MPL Version 2.0</a>"

[[params.footer_rows]]
[[params.footer_rows.items]]
name = "Hugo"
url = "https://gohugo.io"
pre = "Powered by <a href=\"https://gohugo.io\">Hugo</a>"
[[params.footer_rows.items]]
name = "theme flat"
url = "https://cgit.leafee98.com/hugo-theme-flat.git"
pre = "Theme <a href=\"https://git.leafee98.com/leafee98/hugo-theme-flat.git\">hugo-theme-flat</a>"


[[menus.main]]
name = "Posts"
url = "/posts/"
weight = 30

# [[menus.main]]
# name = "Essays"
# url = "/essays/"
# weight = 40

[[menus.main]]
url = "https://adi4web.netlify.app/"
name = "About"
weight = 80

# 2-level sub menus are supported
# [[menus.main]]
# name = "Services"
# weight = 60
# [[menus.main]]
# parent = "Services"
# name = "Service A"
# url = "#"
# [[menus.main]]
# parent = "Services"
# name = "Service B"
# url = "#"
      
[[module]]
  name = "github.com/gohugoio/hugo/modules/favicon"
